@startuml
skinparam defaultFontName Arial

title Federador de Pacientes
hide footbox
participant "CLI" as Sender
participant "FED" as Receiver
group Consulta Directa por ID
"Sender" --> "Receiver" : GET [url_fed]/Patient/[id]
"Receiver" -> "Sender" : response body: {Patient_ar_core}
end
group Consulta por Criterio
"Sender" --> "Receiver" : GET [url_fed]/Patient?[criterio]
"Receiver" -> "Sender" : response body: Bundle <{Patient_ar_core}>
end
group Operacion Búsqueda Candidatos ($match)
"Sender" --> "Receiver" : POST [url_fed]/Patient/$match body:{Patient_ar_core}
"Receiver" -> "Sender" : response body: Bundle <{Patient_ar_core_match}>
end

group Federar Paciente (OK)
"Sender" --> "Receiver" : POST [url_fed]/Patient body:{Patient_ar_core}
"Receiver" -> "Sender" : response body: {Patient_ar_core} con id federador>
end
group Federar Paciente (ERROR)
"Sender" --> "Receiver" : POST [url_fed]/Patient body:{Patient_ar_core}
"Receiver" -> "Sender" : response body: {OperationOutcome} con msg.error
end

@enduml