@startuml
skinparam defaultFontName Arial

title Consultas a REFEPS
hide footbox
participant "CRF" as Sender
participant "REF" as Receiver
group Consulta Directa por ID
"Sender" --> "Receiver" : GET [url_ref]/Practitioner/[id]
"Receiver" -> "Sender" : response body: {Practitioner_ar_core}
end
group Consulta por Criterio
"Sender" --> "Receiver" : GET [url_ref]/Practitioner?[criterio]
"Receiver" -> "Sender" : response body: Bundle <{Practitioner_ar_core}>
end

@enduml