@startuml
skinparam defaultFontName Arial

title Consultas a REFES
hide footbox
participant "CRF" as Sender
participant "REF" as Receiver
group Consulta Directa por ID
"Sender" --> "Receiver" : GET [url_ref]/Organization/[id]
"Receiver" -> "Sender" : response body: {Organization_ar_core}
end
group Consulta por Criterio
"Sender" --> "Receiver" : GET [url_ref]/Organization?[criterio]
"Receiver" -> "Sender" : response body: Bundle <{Organization_ar_core}>
end

@enduml